In [2]:
import numpy as np


In [3]:
np.random.seed(9)
A = np.arange(6).reshape(2, 3)
B = np.arange(12).reshape(3, 4)

In [4]:
A


array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
np.dot(A, B)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [7]:
np.random.seed(9)
a = np.random.randint(10, size=(5))
b = np.random.randint(10, size=(5))

In [8]:
a

array([5, 6, 8, 6, 1])

In [9]:
b

array([6, 4, 8, 1, 8])

In [10]:
np.inner(a, b)

132

In [11]:
np.random.seed(9)
a = np.random.randint(10, size=(5))
b = np.random.randint(10, size=(6))

In [12]:
a
b

array([6, 4, 8, 1, 8, 5])

In [13]:
np.outer(a, b)

array([[30, 20, 40,  5, 40, 25],
       [36, 24, 48,  6, 48, 30],
       [48, 32, 64,  8, 64, 40],
       [36, 24, 48,  6, 48, 30],
       [ 6,  4,  8,  1,  8,  5]])

In [14]:
np.random.seed(9)
A = np.arange(6).reshape(2, 3)
B = np.arange(12).reshape(3, 4)

np.matmul(A, B)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [15]:
np.matmul(A, B)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [16]:
A@B

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [17]:

np.matmul(A, 2)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [18]:
A = np.array([[3, 0, -1],[2, 4, 1],[7, 2, 3]])
A

array([[ 3,  0, -1],
       [ 2,  4,  1],
       [ 7,  2,  3]])

In [19]:
np.trace(A)

10

In [20]:
np.linalg.det(A)

53.999999999999986

In [21]:
np.linalg.inv(A)

array([[ 0.18518519, -0.03703704,  0.07407407],
       [ 0.01851852,  0.2962963 , -0.09259259],
       [-0.44444444, -0.11111111,  0.22222222]])

In [22]:
np.transpose(A)

array([[ 3,  2,  7],
       [ 0,  4,  2],
       [-1,  1,  3]])

In [23]:
B = np.array([[-2, -4, 2],[-2, 1, 2],[4, 2, 5]])
B

array([[-2, -4,  2],
       [-2,  1,  2],
       [ 4,  2,  5]])

In [24]:
w, v = np.linalg.eig(B)

In [25]:
# eigenvalues
w

array([-5.,  3.,  6.])

In [26]:
# eigenvectors
v

array([[ 0.81649658,  0.53452248,  0.05842062],
       [ 0.40824829, -0.80178373,  0.35052374],
       [-0.40824829, -0.26726124,  0.93472998]])

In [27]:
A = np.array([[3, 0, -1],[2, 4, 1],[7, 2, 3]])
np.linalg.matrix_rank(A)

3

In [28]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([2., 3.])

In [29]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])

In [30]:
inv_arrary1 = np.linalg.inv(array1)

In [31]:
is_same = array1@inv_arrary1
is_same

array([[1., 0.],
       [0., 1.]])

In [33]:
#2. 運用上列array計算特徵值、特徵向量?

In [34]:
u, v = np.linalg.eig(array1)

In [35]:
# eigenvalues
u

array([13.,  2.])

In [36]:
# eigenvectors
v

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [37]:
#3. 運用上列array計算SVD?

In [38]:
np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))