In [1]:
import numpy as np

In [2]:
e = np.random.randint(1, 10, 20).reshape(2, 10)
e

array([[8, 7, 8, 1, 2, 2, 9, 1, 9, 4],
       [9, 4, 1, 5, 3, 4, 4, 4, 8, 3]])

In [4]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
a.sum()

45

In [6]:
np.sum(a, axis=0)

array([ 5,  7,  9, 11, 13])

In [7]:
np.power(2, 3)

8

In [8]:
# a 和 b 形狀相同
np.power(a, b)

NameError: name 'b' is not defined

In [9]:
# 與 2**3 相同
np.power(2, 3)

8

In [10]:
np.sqrt(4)

2.0

In [11]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [12]:
np.e

2.718281828459045

In [13]:
np.exp(1)

2.718281828459045

In [14]:
np.exp(np.arange(5))

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [15]:
# 以 np.log10() 為例
np.log10(np.array([1, 10, 100, 1000, 10000]))

array([0., 1., 2., 3., 4.])

In [16]:
np.log(9)/np.log(3)

2.0

In [18]:
np.log([-1, 1, 2])

array([       nan, 0.        , 0.69314718])

In [19]:
a = np.array([1.65, 1.55, -3.57, 2.0])
a

array([ 1.65,  1.55, -3.57,  2.  ])

In [20]:
np.round(a, decimals=1)


array([ 1.6,  1.6, -3.6,  2. ])

In [21]:
# Round至最近的整數
np.rint(a)

array([ 2.,  2., -4.,  2.])

In [22]:
# 無條件捨去小數點
np.trunc(a)

array([ 1.,  1., -3.,  2.])

In [23]:
# 向下取整數
np.floor(a)

array([ 1.,  1., -4.,  2.])

In [24]:
# 向上取整數
np.ceil(a)

array([ 2.,  2., -3.,  2.])

In [25]:
# 向0的方向取整數
np.fix(a)

array([ 1.,  1., -3.,  2.])

In [26]:
a

array([ 1.65,  1.55, -3.57,  2.  ])

In [27]:
np.abs(a)

array([1.65, 1.55, 3.57, 2.  ])

In [28]:
np.fabs(1+2j)

TypeError: ufunc 'fabs' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [30]:
#1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?
#請寫下程式
V1 = 20000
V0 = 20

In [33]:
y = 20*np.log10(V1/V0)
y

60.0

In [37]:
z = (10**1.5)/(10**2.5)
z

0.09999999999999999