In [2]:
import numpy as np

In [3]:
a = np.array([[ 0,  1,  2,  3], 
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
b[b%2==0] = 0
b

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11])

In [8]:
a

array([[ 0,  1,  0,  3],
       [ 0,  5,  0,  7],
       [ 0,  9,  0, 11]])

In [9]:
a.flatten()

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11])

In [10]:
a.ravel(order='C')

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11])

In [11]:
a.ravel(order='F')

array([ 0,  0,  0,  1,  5,  9,  0,  0,  0,  3,  7, 11])

In [12]:
type(a)

numpy.ndarray

In [20]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
c = a.reshape((10,2))
c[9,1] = 517
c

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9],
       [ 10,  11],
       [ 12,  13],
       [ 14,  15],
       [ 16,  17],
       [ 18, 517]])

In [31]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18, 517])

In [33]:
a[19] = 19

In [34]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
a.reshape((10,-1))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [50]:
b = np.arange(15)

In [51]:
b.resize((3, 5))
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
b.resize(3,refcheck=False)

In [53]:
b

array([0, 1, 2])

In [54]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [55]:
a = np.array([[[1, 2, 3], [4, 5, 6],
              [7, 8, 9], [10, 11, 12]],
              [[1, 2, 3], [4, 5, 6],
              [7, 8, 9], [10, 11, 12]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
a.shape

(2, 4, 3)

In [57]:

a.sum(axis=0)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [58]:
a = np.arange(12).reshape(2, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [59]:
a[:,np.newaxis,:].shape

(2, 1, 6)

In [60]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [61]:
a[:,:,np.newaxis].shape


(2, 6, 1)

In [62]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [63]:
a = np.arange(10).reshape(5, 2)
b = np.arange(6).reshape(3, 2)

In [64]:
np.concatenate((a,b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5]])

In [65]:
c = np.arange(10).reshape(5, 2)

In [66]:
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [67]:
np.stack((a, c), axis=1)

array([[[0, 1],
        [0, 1]],

       [[2, 3],
        [2, 3]],

       [[4, 5],
        [4, 5]],

       [[6, 7],
        [6, 7]],

       [[8, 9],
        [8, 9]]])

In [68]:
np.stack((a, c), axis=0)

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]],

       [[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]])

In [69]:
cc = np.stack((a, c), axis=1)
cc.size

20

In [70]:
cc

array([[[0, 1],
        [0, 1]],

       [[2, 3],
        [2, 3]],

       [[4, 5],
        [4, 5]],

       [[6, 7],
        [6, 7]],

       [[8, 9],
        [8, 9]]])

In [71]:
np.hstack((a, c))

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7],
       [8, 9, 8, 9]])

In [72]:
np.vstack((a, b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5]])

In [73]:
a = np.arange(10).reshape(5, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [74]:
np.split(a,5)

[array([[0, 1]]),
 array([[2, 3]]),
 array([[4, 5]]),
 array([[6, 7]]),
 array([[8, 9]])]

In [76]:
np.split(a,2,axis=1)

[array([[0],
        [2],
        [4],
        [6],
        [8]]),
 array([[1],
        [3],
        [5],
        [7],
        [9]])]

In [77]:
# split 為 (2,2), (1,2), (2,2) 三個陣列，並回傳含 3 個陣列的 List
np.split(a, [2,3])

[array([[0, 1],
        [2, 3]]),
 array([[4, 5]]),
 array([[6, 7],
        [8, 9]])]

In [78]:
b = np.arange(30).reshape(5, 6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [79]:
np.hsplit(b, 3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29]])]

In [80]:
np.hsplit(b, 2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29]])]

In [81]:
np.hsplit(b, [2, 3, 5])

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]),
 array([[ 2],
        [ 8],
        [14],
        [20],
        [26]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29]])]

In [82]:
# 依垂直軸按照區段去分割，超出的區段則傳回空陣列
np.vsplit(b, [2, 4, 6])

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29]]),
 array([], shape=(0, 6), dtype=int32)]

In [83]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [84]:
for i in a:
    print(i)

0
1
2
3
4


In [85]:
b = np.arange(6).reshape(2, 3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [86]:
for row in b:
    print(row)

[0 1 2]
[3 4 5]


In [87]:
for i in b.flat:
    print(i)

0
1
2
3
4
5


In [88]:
a = np.random.randint(1, 20, 10)
a

array([16, 19, 10, 19, 19, 15, 18,  4, 10, 17])

In [89]:
np.amax(a)

19

In [90]:
np.amin(a)

4

In [91]:
b = a.reshape(2, 5)
b

array([[16, 19, 10, 19, 19],
       [15, 18,  4, 10, 17]])

In [92]:
np.amax(b, keepdims=True)

array([[19]])

In [93]:
np.amax(b)

19

In [94]:
# 同樣的 amax 也可以依軸列出各 row 最大值
np.amax(b, axis=1)

array([19, 18])

In [95]:
# 列出各 column 最小值
b.min(axis=0)

array([15, 18,  4, 10, 17])

In [96]:
np.random.seed(0)
a = np.random.randint(1, 20, size=(3, 4))
a

array([[13, 16,  1,  4],
       [ 4,  8, 10, 19],
       [ 5,  7, 13,  2]])

In [97]:
np.argmax(a)

7

In [98]:
np.amax(a)

19

In [99]:
np.amax(a, keepdims=True)

array([[19]])

In [101]:
np.argmax(a, axis=0)

array([0, 0, 2, 1], dtype=int64)

In [102]:
np.argmax(a, axis=1)

array([1, 3, 2], dtype=int64)

In [103]:
# 元素值 1 為最小值，展平後的索引值為 2。
a.argmin()

2

In [104]:
a

array([[13, 16,  1,  4],
       [ 4,  8, 10, 19],
       [ 5,  7, 13,  2]])

In [105]:
np.where(a > 10)

(array([0, 0, 1, 2], dtype=int64), array([0, 1, 3, 2], dtype=int64))

In [106]:
np.where(a > 10, "Y", "N")

array([['Y', 'Y', 'N', 'N'],
       ['N', 'N', 'N', 'Y'],
       ['N', 'N', 'Y', 'N']], dtype='<U1')

In [107]:
np.random.seed(2)
a = np.random.randint(0, 5, 10)
a

array([0, 0, 3, 2, 3, 0, 2, 1, 3, 2])

In [108]:

np.nonzero(a)

(array([2, 3, 4, 6, 7, 8, 9], dtype=int64),)

In [109]:
a.nonzero()

(array([2, 3, 4, 6, 7, 8, 9], dtype=int64),)

In [110]:
np.random.seed(3)
a = np.random.randint(0, 20, 10)
a

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6])

In [111]:
np.sort(a)

array([ 0,  3,  6,  8,  9, 10, 10, 10, 11, 19])

In [112]:
a.argsort()

array([3, 1, 9, 2, 7, 0, 5, 8, 6, 4], dtype=int64)

In [113]:
a.sort()
a

array([ 0,  3,  6,  8,  9, 10, 10, 10, 11, 19])

In [114]:
b = np.random.randint(0, 20, size=(5, 4))
b

array([[ 0, 12,  7, 14],
       [17,  2,  2,  1],
       [19,  5,  8, 14],
       [ 1, 10,  7, 11],
       [ 1, 15, 16,  5]])

In [115]:
np.sort(b, axis=0)

array([[ 0,  2,  2,  1],
       [ 1,  5,  7,  5],
       [ 1, 10,  7, 11],
       [17, 12,  8, 14],
       [19, 15, 16, 14]])

In [116]:
c = np.random.randint(0, 100000000, 1000000)
np.sort(c, kind='heapsort')

array([      64,       96,      310, ..., 99999479, 99999561, 99999830])

In [117]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))

In [118]:
array1.reshape(5, 6, order='F')

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [119]:
#2.呈上題的array，找出被6除餘1的數的索引

In [122]:
array1.argsort(array1(array1%7==0))//failed1

TypeError: 'numpy.ndarray' object is not callable

In [123]:
c = array1.reshape(5, 6, order='F')//failed2

In [124]:
c.argsort(c(c%7==0)) //failed2

TypeError: 'numpy.ndarray' object is not callable

In [125]:
np.where(c%7==0) //failed3

(array([0, 1, 2, 3, 4], dtype=int64), array([0, 4, 1, 5, 2], dtype=int64))

In [126]:
np.where(c%7==0, axis = 0) //failed4

TypeError: where() got an unexpected keyword argument 'axis'

In [127]:
np.where(c%6==1) //success

(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))