In [2]:
import numpy as np


In [3]:
np.random.seed(9)
A = np.arange(6).reshape(2, 3)
B = np.arange(12).reshape(3, 4)

In [4]:
A


array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
np.dot(A, B)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [7]:
np.random.seed(9)
a = np.random.randint(10, size=(5))
b = np.random.randint(10, size=(5))

In [8]:
a

array([5, 6, 8, 6, 1])

In [9]:
b

array([6, 4, 8, 1, 8])

In [10]:
np.inner(a, b)

132

In [11]:
np.random.seed(9)
a = np.random.randint(10, size=(5))
b = np.random.randint(10, size=(6))

In [12]:
a
b

array([6, 4, 8, 1, 8, 5])

In [13]:
np.outer(a, b)

array([[30, 20, 40,  5, 40, 25],
       [36, 24, 48,  6, 48, 30],
       [48, 32, 64,  8, 64, 40],
       [36, 24, 48,  6, 48, 30],
       [ 6,  4,  8,  1,  8,  5]])

In [14]:
np.random.seed(9)
A = np.arange(6).reshape(2, 3)
B = np.arange(12).reshape(3, 4)

np.matmul(A, B)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [15]:
np.matmul(A, B)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [16]:
A@B

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [17]:

np.matmul(A, 2)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [18]:
A = np.array([[3, 0, -1],[2, 4, 1],[7, 2, 3]])
A

array([[ 3,  0, -1],
       [ 2,  4,  1],
       [ 7,  2,  3]])

In [19]:
np.trace(A)

10

In [20]:
np.linalg.det(A)

53.999999999999986

In [21]:
np.linalg.inv(A)

array([[ 0.18518519, -0.03703704,  0.07407407],
       [ 0.01851852,  0.2962963 , -0.09259259],
       [-0.44444444, -0.11111111,  0.22222222]])

In [22]:
np.transpose(A)

array([[ 3,  2,  7],
       [ 0,  4,  2],
       [-1,  1,  3]])

In [23]:
B = np.array([[-2, -4, 2],[-2, 1, 2],[4, 2, 5]])
B

array([[-2, -4,  2],
       [-2,  1,  2],
       [ 4,  2,  5]])

In [24]:
w, v = np.linalg.eig(B)

In [25]:
# eigenvalues
w

array([-5.,  3.,  6.])

In [26]:
# eigenvectors
v

array([[ 0.81649658,  0.53452248,  0.05842062],
       [ 0.40824829, -0.80178373,  0.35052374],
       [-0.40824829, -0.26726124,  0.93472998]])

In [27]:
A = np.array([[3, 0, -1],[2, 4, 1],[7, 2, 3]])
np.linalg.matrix_rank(A)

3

In [28]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([2., 3.])

In [29]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])

In [30]:
inv_arrary1 = np.linalg.inv(array1)

In [31]:
is_same = array1@inv_arrary1
is_same

array([[1., 0.],
       [0., 1.]])

In [33]:
#2. 運用上列array計算特徵值、特徵向量?

In [34]:
u, v = np.linalg.eig(array1)

In [35]:
# eigenvalues
u

array([13.,  2.])

In [36]:
# eigenvectors
v

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [37]:
#3. 運用上列array計算SVD?

In [38]:
np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))

In [1]:
# 從陣列中存取元素



L = [0, 1, 8]

print(L)
print(L[-1]) # 8
print(L[0]) # 0
print(L[1:3]) # [1, 8]

[0, 1, 8]
8
0
[1, 8]


In [3]:
import numpy as np 

a = np.arange(3) ** 3

print(a)
print(a[-1]) # 8
print(a[0]) # 0
print(a[1:3]) # [1 8]

[0 1 8]
8
0
[1 8]


In [4]:
# 一維陣列的切片與索引

import numpy as np 

data = np.array([1, 2, 3])

print(data[0]) # 取出第 0 個
print(data[1]) # 取出第 1 個
print(data[0:2]) # 第 0 - 1 個
print(data[1:]) # 第 1 到最後一個
print(data[-2:]) # 倒數第二到最後一個

1
2
[1 2]
[2 3]
[2 3]


In [7]:
# 一維陣列的的迭代

import numpy as np 

a = np.arange(3)**3

for i in a:
    print(i)
# 0
# 1 
# 8

0
1
8


In [8]:
# 多維陣列的多層迴圈

import numpy as np 

a = np.arange(6).reshape(3, 2)

for row in a:
    print(row)
# [0 1]
# [2 3]
# [4 5]

[0 1]
[2 3]
[4 5]


In [9]:
for row in a:
    for d in row:
        print(d)
# 0
# 1
# 2
# 3
# 4
# 5

0
1
2
3
4
5


In [10]:
# 攤平後再迭代多維陣列

import numpy as np 

a = np.arange(6).reshape(3, 2)

for d in a.flat:
    print(d)

0
1
2
3
4
5


In [14]:
# np.nditer 迭代物件

import numpy as np 

a = np.arange(6).reshape(3, 2)

for d in np.nditer(a):
    print(d)

0
1
2
3
4
5


In [15]:
# 迭代物件的儲存方向

a = np.arange(6).reshape(3, 2)

for d in np.nditer(a, order='C'):
    print(d)


0
1
2
3
4
5


In [17]:
# 迭代物件的儲存方向

a = np.arange(6).reshape(3, 2)

for d in np.nditer(a, order='F'):
    print(d)


0
2
4
1
3
5


In [18]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [19]:
%timeit -n 10 a = 2

35.7 ns ± 7.28 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [21]:
y = Z + 1
%timeit -n 10 a = 2

35.7 ns ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [22]:
Z

array([[[4, 8, 5, ..., 8, 2, 8],
        [2, 7, 0, ..., 0, 3, 5],
        [0, 5, 2, ..., 1, 6, 7],
        ...,
        [8, 1, 5, ..., 8, 0, 5],
        [1, 6, 3, ..., 0, 4, 0],
        [6, 0, 8, ..., 5, 8, 3]],

       [[7, 7, 3, ..., 9, 2, 8],
        [3, 7, 7, ..., 3, 9, 1],
        [8, 3, 2, ..., 6, 5, 3],
        ...,
        [2, 9, 1, ..., 5, 9, 8],
        [6, 7, 5, ..., 4, 6, 7],
        [2, 0, 2, ..., 7, 3, 2]],

       [[5, 6, 9, ..., 3, 6, 5],
        [1, 4, 5, ..., 8, 1, 8],
        [7, 4, 1, ..., 5, 7, 5],
        ...,
        [8, 3, 0, ..., 5, 3, 2],
        [9, 9, 9, ..., 5, 8, 4],
        [6, 3, 7, ..., 1, 9, 9]],

       ...,

       [[3, 0, 9, ..., 3, 0, 7],
        [7, 3, 6, ..., 3, 5, 0],
        [9, 4, 6, ..., 1, 1, 0],
        ...,
        [4, 7, 5, ..., 7, 3, 5],
        [3, 9, 4, ..., 9, 6, 5],
        [7, 1, 3, ..., 1, 1, 4]],

       [[7, 7, 1, ..., 8, 2, 9],
        [1, 5, 0, ..., 4, 3, 8],
        [5, 5, 4, ..., 6, 9, 4],
        ...,
        [2, 9, 3, ..., 

In [24]:
y= 0
for row in Z:
    row += 1
    
%timeit -n 10 a = 2
    

72.9 ns ± 4.52 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
y= 0
for row in Z:
    for i in row:
        i += 1
    
%timeit -n 10 a = 2
    

34.3 ns ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
